[package]
name = "ckb-debugger-dumper"
version = "0.100.0-rc2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-vm = "=0.20.0-rc1"
ckb-jsonrpc-types = "0.100.0-rc2"
ckb-chain-spec = "0.100.0-rc2"
ckb-script = "0.100.0-rc2"
ckb-types = "0.100.0-rc2"
ckb-error = "0.100.0-rc2"
ckb-traits = "0.100.0-rc2"
ckb-crypto = "0.100.0-rc2"
ckb-hash = "0.100.0-rc2"
json = "0.12.4"
molecule = "0.7.1"

[dev-dependencies]
lazy_static = "1.3.0"
rand = "0.6.5"
