[package]
name = "ckb-debugger-dumper"
version = "0.100.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-script = "0.100.0"
ckb-types = "0.100.0"
ckb-traits = "0.100.0"
json = "0.12.4"
molecule = "0.7.1"

[dev-dependencies]
ckb-vm = "=0.20.0-rc5"
ckb-chain-spec = "=0.100.0"
lazy_static = "1.3.0"
rand = "0.6.5"
